from playwright.sync_api import sync_playwright
URL = "http://127.0.0.1:8765/index.html"
errors = []
with sync_playwright() as p:
    b = p.chromium.launch(args=["--autoplay-policy=no-user-gesture-required"])
    ctx = b.new_context(viewport={"width": 390, "height": 844}, has_touch=True)
    page = ctx.new_page()
    page.on("console", lambda m: errors.append((m.type, m.text)) if m.type == "error" else None)
    page.on("pageerror", lambda e: errors.append(("pageerror", str(e))))
    page.goto(URL)
    page.wait_for_function("document.documentElement.dataset.ready === 'true'", timeout=20000)
    page.wait_for_function("!kittycat.ctl.isDealing", timeout=20000)
    page.wait_for_timeout(500)
    page.locator(".pile.stock .card").first.tap()
    page.wait_for_function("kittycat.fx.ready && Object.keys(kittycat.fx.buffers).length === 4", timeout=20000)
    page.wait_for_timeout(2000)
    print("decoded effects:", page.evaluate("Object.fromEntries(Object.entries(kittycat.fx.buffers).map(([k, v]) => [k, v.map(b => Math.round(b.duration * 1000) + ' ms')]))"))
    print("music listed:", page.evaluate("kittycat.fx.manifest.music"))
    page.evaluate("""() => { window.__plays = 0; const ctx = kittycat.fx.ctx; const orig = ctx.createBufferSource.bind(ctx);
        ctx.createBufferSource = () => { window.__plays++; return orig(); }; }""")
    plays = lambda: page.evaluate("window.__plays")
    def act(): page.evaluate("async () => { const E = await import('./js/engine.js'); kittycat.ctl.perform(E.DRAW); }")
    n0 = plays(); act(); print("effects on     -> sounds played:", plays() - n0)
    page.evaluate("kittycat.settings.set('effectsOn', false)")
    n0 = plays(); act(); print("effects off    -> sounds played:", plays() - n0)
    page.evaluate("kittycat.settings.set('effectsOn', true); kittycat.settings.set('soundsOn', false)")
    n0 = plays(); act(); print("all sounds off -> sounds played:", plays() - n0)
    page.evaluate("kittycat.settings.set('soundsOn', true)")
    print("music is off by default:", page.evaluate("!kittycat.fx.musicEl"))
    page.evaluate("kittycat.settings.set('musicOn', true)")
    page.wait_for_timeout(2500)
    print("music on       -> playing:", page.evaluate("!!kittycat.fx.musicEl && !kittycat.fx.musicEl.paused"), "| gain", page.evaluate("kittycat.fx.musicGain ? kittycat.fx.musicGain.gain.value.toFixed(2) : null"))
    page.evaluate("kittycat.settings.set('soundsOn', false)"); page.wait_for_timeout(1500)
    print("all sounds off -> music paused:", page.evaluate("kittycat.fx.musicEl ? kittycat.fx.musicEl.paused : 'no element'"))
    page.evaluate("kittycat.settings.set('soundsOn', true)"); page.wait_for_timeout(1500)
    print("all sounds on  -> music playing:", page.evaluate("!!kittycat.fx.musicEl && !kittycat.fx.musicEl.paused"))
    page.evaluate("kittycat.settings.set('musicOn', false)"); page.wait_for_timeout(1500)
    print("music switch off -> paused:", page.evaluate("kittycat.fx.musicEl ? kittycat.fx.musicEl.paused : 'no element'"))
    page.locator("#menuBtn").click(); page.get_by_role("menuitem", name="Settings").click(); page.wait_for_timeout(300)
    page.get_by_role("button", name="Sound credits").click(); page.wait_for_timeout(400)
    txt = page.evaluate("document.querySelector('pre.credits').textContent")
    print("credits screen:", txt.splitlines()[0], "| Yoiyami:", "Yoiyami" in txt, "| Cynic:", "Cynic" in txt, "| Kenney:", "Kenney" in txt)
    page.keyboard.press("Escape")
    page.wait_for_function("navigator.serviceWorker.ready.then(r => !!r.active)")
    page.reload(); page.wait_for_function("document.documentElement.dataset.ready === 'true'")
    print("cache:", page.evaluate("caches.keys().then(async ks => { const c = await caches.open(ks[0]); const r = await c.keys(); return {cache: ks[0], files: r.length, sounds: r.filter(x => x.url.includes('/sounds/')).length}; })"))
    ctx.set_offline(True)
    page.reload(); page.wait_for_function("document.documentElement.dataset.ready === 'true'")
    page.locator(".pile.stock .card").first.tap()
    page.wait_for_function("kittycat.fx.ready && Object.keys(kittycat.fx.buffers).length === 4", timeout=20000)
    page.wait_for_timeout(1500)
    print("OFFLINE decoded groups:", page.evaluate("Object.fromEntries(Object.entries(kittycat.fx.buffers).map(([k, v]) => [k, v.length]))"))
    print("errors:", errors)
    b.close()
